from website.models import db, User, Vehicle, bcrypt, login_manager
from flask import Flask, render_template
from website.views import views
from website.auth import auth
from datetime import datetime
from os import path
import sqlalchemy
import os
import certifi

os.environ["SSL_CERT_FILE"]= certifi.where()
app=Flask(__name__)
app.config['SECRET_KEY']= 'c74c5f93863c5b92b46fb676'
app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False


# Construct a DATABASE_URL only if the DATABASE_USER and DATABASE_PASSWORD variables exist
if os.getenv("DATABASE_USER") and os.getenv("DATABASE_PASSWORD"):
    database_user = os.getenv('DATABASE_USER')
    database_password = os.getenv('DATABASE_PASSWORD')
    app.config['SQLALCHEMY_DATABASE_URI'] = f"mysql+pymysql://{database_user}:{database_password}@/database?unix_socket=/cloudsql/luxurywheels:europe-southwest1:database"
elif os.getenv("DATABASE_URL"):
    # Use DATABASE_URL if defined
    app.config['SQLALCHEMY_DATABASE_URI'] = os.getenv('DATABASE_URL')
else:
    # Fallback to local SQLite if none of the previous variables are set
    app.config['SQLALCHEMY_DATABASE_URI'] = "sqlite:///C:\\Users\\Gabriel\\.vscode\\GitHub\\LuxuryWheels\\website\\database/database.db"


db.init_app(app)
bcrypt.init_app(app)
login_manager.init_app(app)
login_manager.login_view= "auth.login_page"
login_manager.login_message_category='info'

app.register_blueprint(views, prefix_url='/')
app.register_blueprint(auth, prefix_url='/')

# create engine to check if database already exists
engine = sqlalchemy.create_engine(app.config['SQLALCHEMY_DATABASE_URI'])
inspector = sqlalchemy.inspect(engine)

if not inspector.has_table("user"):  

    with app.app_context():    
        db.drop_all()
        db.create_all()
       
        audiR81=Vehicle(item_name="Audi",item_type= "Car", item_model= "R8" , item_price= 600,daily_price= 29,item_barcode="783511" , passengers= 2,doors= 2, AC= "Yes", fuel="Gasoline", baggage= "Yes", gear= "7, Manual", power= 602, co2=293 ,image= "audicarroperfil.jpg", last_review=datetime.strptime("15/11/2023", "%d/%m/%Y").date(), next_review=datetime.strptime("15/02/2024", "%d/%m/%Y").date(), inspection=datetime.strptime("15/06/2023", "%d/%m/%Y").date(), desc="Discover the perfect union of performance and sophistication in the Audi R8. This automotive icon is not just a car; it's an engineering masterpiece, designed to elevate every journey to an unforgettable experience. With fluid lines that evoke movement even at rest, the R8 is a vision of pure elegance. \n\nUnder the hood lies a fierce heart: a V10 engine that delivers extraordinary performance, harmonized with a symphony of power that resonates with every acceleration. The precision of its handling, coupled with an interior meticulously designed for comfort and luxury, makes the Audi R8 more than a vehicle - it's a sanctuary of speed and style. \n\nEvery detail of the R8 has been thoughtfully considered, from the high-quality finishes to the cutting-edge technology, ensuring a driving experience that is both intuitive and exhilarating. This is not just a car to be seen - it is a car to be felt. \n\nIn the Audi R8, every journey is an adventure, every road a promise of unparalleled excitement. Come and feel the power, passion, and prestige that only the Audi R8 can offer.")
        audiR82=Vehicle(item_name="Audi",item_type= "Car", item_model= "R8" , item_price= 600,daily_price= 29,item_barcode="783512", passengers= 2,doors= 2, AC= "Yes", fuel="Gasoline", baggage= "Yes", gear= "7, Manual", power= 602, co2=301 ,image= "audir8carro.jpeg",last_review=datetime.strptime("10/10/2023", "%d/%m/%Y").date(), next_review=datetime.strptime("10/10/2024", "%d/%m/%Y").date(), inspection=datetime.strptime("20/02/2023", "%d/%m/%Y").date(), desc="Step into a realm where opulence seamlessly intertwines with versatility—the Audi Q7. This SUV is not merely a vehicle; it's a statement of refined taste and a commitment to an unparalleled driving experience. <br> From its spacious, meticulously crafted interior to the commanding presence it exudes on the road, the Q7 is a symbol of automotive excellence. Designed for those who crave more from their journeys, the Audi Q7 effortlessly combines performance and comfort. As you embark on each adventure, revel in the harmonious blend of power and sophistication. \nThe Q7 isn't just a mode of transportation; it's an embodiment of your discerning lifestyle. \nWhether navigating city streets or conquering off-road terrain, the Audi Q7 adapts with grace and poise. Every detail, from the whisper-quiet cabin to the cutting-edge technology, reflects Audi's unwavering commitment to craftsmanship. Elevate your driving experience with the Audi Q7—a masterpiece of luxury and adventure.")
        audiQ71=Vehicle(item_name="Audi",item_type= "Suv", item_model= "Q7" , item_price= 600,daily_price= 29,item_barcode="783513", passengers= 7,doors= 4, AC= "Yes", fuel="Gasoline", baggage= "Yes", gear= "8, Automatic", power= 248, co2=190 ,image= "audisuv(2).jpeg",last_review=datetime.strptime("19/04/2023", "%d/%m/%Y").date(), next_review=datetime.strptime("19/04/2024", "%d/%m/%Y").date(), inspection=datetime.strptime("10/03/2023", "%d/%m/%Y").date(), desc="Discover the Citroen C4, a masterpiece of automotive design that transcends the ordinary. \nWith its striking lines and innovative features, the C4 is not just a car; it's a statement of modern elegance and advanced technology. Step into a cockpit designed for comfort and connectivity, where every detail reflects Citroen's commitment to craftsmanship. \nThe C4 seamlessly blends performance and efficiency, making each drive a delightful journey. \n Whether navigating urban landscapes or cruising on the open road, the Citroen C4 delivers a driving experience that goes beyond expectations. Embrace a new era of automotive excellence with the Citroen C4—a car that redefines your connection with the road.")
        audiQ72=Vehicle(item_name="Audi",item_type= "Suv", item_model= "Q7" , item_price= 600,daily_price= 29,item_barcode="783514", passengers= 7,doors= 4, AC= "Yes", fuel="Gasoline", baggage= "Yes", gear= "8, Automatic", power= 248, co2=190 ,image= "Audisuv.jpeg", last_review=datetime.strptime("03/04/2023", "%d/%m/%Y").date(), next_review=datetime.strptime("03/04/2024", "%d/%m/%Y").date(), inspection=datetime.strptime("14/07/2023", "%d/%m/%Y").date(),desc="Embark on a journey of boundless possibilities with the Ford Ranger. This robust and versatile pickup truck is more than a vehicle; it's a companion for those who seek both rugged durability and refined craftsmanship. Designed to conquer both city streets and off-road terrain, the Ford Ranger effortlessly combines power with precision. \nFrom its commanding presence to the meticulously crafted interior, every aspect speaks to Ford's commitment to excellence. Step into the driver's seat and experience a blend of performance and comfort that defines the Ranger's character. \nWith innovative features and cutting-edge technology, the Ranger transforms every drive into an adventure. \nWhether it's tackling tough jobs or exploring the great outdoors, the Ford Ranger stands ready to elevate your driving experience. Embrace the spirit of adventure with the Ford Ranger—a pickup that goes beyond the ordinary.")
        citroenC4=Vehicle(item_name="Citroen",item_type= "Car", item_model= "C4" , item_price= 50,daily_price= 8, item_barcode="783515", passengers= 5,doors= 5, AC= "Yes", fuel="Diesel", baggage= "Yes", gear= "5, Manual", power= 130, co2=119 ,image= "citroencarro.jpeg", last_review=datetime.strptime("10/10/2023", "%d/%m/%Y").date(), next_review=datetime.strptime("10/10/2024", "%d/%m/%Y").date(), inspection=datetime.strptime("13/08/2023", "%d/%m/%Y").date(),desc="Introducing the Mercedes Classe A, where sophistication meets cutting-edge technology. This compact luxury car is more than a mode of transportation; it's a symbol of refined taste and automotive excellence. \nWith its sleek design and premium interior, the Classe A captivates at first glance. Step inside to experience a harmonious blend of comfort and innovation. The meticulous craftsmanship and attention to detail elevate every aspect of your driving experience. Navigate urban streets with agility and style, thanks to the Classe A's dynamic performance and advanced features. \nFrom its powerful engine to the latest in connectivity, this car seamlessly integrates luxury into every journey. \nWhether it's the daily commute or a weekend getaway, the Mercedes Classe A delivers a driving experience that transcends expectations. Elevate your presence on the road with the embodiment of elegance—the Mercedes Classe A.")
        fordRanger=Vehicle(item_name="Ford",item_type= "Suv", item_model= "Ranger" , item_price= 250,daily_price= 15,item_barcode="783516", passengers= 5,doors= 4, AC= "Yes", fuel="Gasoline", baggage= "Yes", gear= "6, Manual", power= 150, co2=258 ,image= "fordsuv.jpeg", last_review=datetime.strptime("10/11/2023", "%d/%m/%Y").date(), next_review=datetime.strptime("10/11/2024", "%d/%m/%Y").date(), inspection=datetime.strptime("17/03/2023", "%d/%m/%Y").date(),desc="Experience the epitome of driving pleasure with the Mercedes SLK. This convertible roadster is not just a car; it's an embodiment of freedom and exhilaration. /nFrom its sleek, aerodynamic design to the open-air cockpit, the SLK invites you to indulge in the joy of the open road. Step into a world of refined luxury where every detail is meticulously crafted. /nThe SLK's interior harmonizes comfort with performance, creating an atmosphere that enhances every moment behind the wheel. With the retractable hardtop, seamlessly switch between the thrill of top-down cruising and the comfort of a coupe. /nThe SLK isn't just a vehicle; it's a celebration of driving dynamics, delivering a perfect balance of power and grace. Whether navigating winding roads or cruising through the city, the Mercedes SLK transforms every drive into an adventure. Embrace the allure of open-air motoring with the Mercedes SLK—an icon of timeless elegance and spirited performance.")
        mercedesA=Vehicle(item_name="Mercedes",item_type= "Car", item_model= "Classe A" , item_price= 250,daily_price= 15,item_barcode="783517", passengers= 5,doors= 4, AC= "Yes", fuel="Hybrid", baggage= "Yes", gear= "7, Automatic", power= 136, co2=122 ,image= "mercedescarro (2).jpeg", last_review=datetime.strptime("10/12/2023", "%d/%m/%Y").date(), next_review=datetime.strptime("10/12/2024", "%d/%m/%Y").date(), inspection=datetime.strptime("18/03/2023", "%d/%m/%Y").date(),desc="Introducing the Mercedes Classe A, where sophistication meets cutting-edge technology. This compact luxury car is more than a mode of transportation; it's a symbol of refined taste and automotive excellence. \nWith its sleek design and premium interior, the Classe A captivates at first glance. Step inside to experience a harmonious blend of comfort and innovation. The meticulous craftsmanship and attention to detail elevate every aspect of your driving experience. Navigate urban streets with agility and style, thanks to the Classe A's dynamic performance and advanced features. \nFrom its powerful engine to the latest in connectivity, this car seamlessly integrates luxury into every journey. \nWhether it's the daily commute or a weekend getaway, the Mercedes Classe A delivers a driving experience that transcends expectations. Elevate your presence on the road with the embodiment of elegance—the Mercedes Classe A.")
        mercedesslk=Vehicle(item_name="Mercedes",item_type= "Car", item_model= "SLK" , item_price= 50,daily_price= 8,item_barcode="783518", passengers= 5,doors= 5, AC= "Yes", fuel="Hybrid", baggage= "Yes", gear= "9, Automatic", power= 197, co2=138 ,image= "mercedescarro (3).jpeg", last_review=datetime.strptime("25/09/2023", "%d/%m/%Y").date(), next_review=datetime.strptime("25/09/2024", "%d/%m/%Y").date(), inspection=datetime.strptime("19/05/2023", "%d/%m/%Y").date(),desc="Experience the epitome of driving pleasure with the Mercedes SLK. This convertible roadster is not just a car; it's an embodiment of freedom and exhilaration. \nFrom its sleek, aerodynamic design to the open-air cockpit, the SLK invites you to indulge in the joy of the open road. Step into a world of refined luxury where every detail is meticulously crafted. \nThe SLK's interior harmonizes comfort with performance, creating an atmosphere that enhances every moment behind the wheel. With the retractable hardtop, seamlessly switch between the thrill of top-down cruising and the comfort of a coupe. \nThe SLK isn't just a vehicle; it's a celebration of driving dynamics, delivering a perfect balance of power and grace. \nWhether navigating winding roads or cruising through the city, the Mercedes SLK transforms every drive into an adventure. Embrace the allure of open-air motoring with the Mercedes SLK—an icon of timeless elegance and spirited performance.")
        mercedesCE=Vehicle(item_name="Mercedes",item_type= "Car", item_model= "Classe E" , item_price= 250,daily_price= 15,item_barcode="783519", passengers= 5,doors= 4, AC= "Yes", fuel="Eletric", baggage= "Yes", gear= "9, Automatic", power= 258, co2=163 ,image= "Mercedescarro.jpeg", last_review=datetime.strptime("19/06/2023", "%d/%m/%Y").date(), next_review=datetime.strptime("19/06/2024", "%d/%m/%Y").date(), inspection=datetime.strptime("16/08/2023", "%d/%m/%Y").date(),desc="Introducing the Peugeot 207, where chic design harmonizes with everyday practicality. This compact car is not just a vehicle; it's a symbol of effortless style and versatility. /nWith its distinctive exterior and thoughtfully crafted interior, the Peugeot 207 stands out in the crowd. Step into a space where comfort and functionality seamlessly blend, creating an inviting atmosphere for every drive. /nEfficiency takes center stage with the Peugeot 207's nimble performance and fuel economy. Whether maneuvering through city streets or embarking on a spontaneous road trip, this car delivers a driving experience that is both enjoyable and reliable. /nThe Peugeot 207 is more than a car; it's a companion for the modern driver. Embrace the perfect union of style and practicality with a vehicle that makes every journey a delightful adventure.")
        opelAstra=Vehicle(item_name="Opel",item_type= "Car", item_model= "Astra" , item_price= 250,daily_price= 15,item_barcode="783520", passengers= 5,doors= 5, AC= "Yes", fuel="Diesel", baggage= "Yes", gear= "6, Manual", power= 150, co2=115 ,image= "opelcarro.jpeg", last_review=datetime.strptime("10/05/2023", "%d/%m/%Y").date(), next_review=datetime.strptime("10/05/2024", "%d/%m/%Y").date(), inspection=datetime.strptime("19/04/2023", "%d/%m/%Y").date(),desc="Indulge in the epitome of luxury and performance with the Porsche Panamera. This executive sedan transcends the ordinary, offering a driving experience that seamlessly blends power with sophistication. /nFrom its striking exterior to the meticulously crafted interior, the Panamera captivates with its timeless design and attention to detail. Step inside to discover a world where opulence meets cutting-edge technology, creating a cockpit designed for the discerning driver. /nPerformance is at the heart of the Panamera, with a powerful engine and precision engineering that ensures a thrilling ride on every journey. Whether cruising down the highway or navigating city streets, this sedan delivers a dynamic driving experience that sets it apart. /nThe Porsche Panamera is not just a car; it's a statement of automotive excellence. Elevate your driving passion with a vehicle that defines the pinnacle of luxury and performance.")
        peugeot207=Vehicle(item_name="Peugeot",item_type= "Car", item_model= "207" , item_price= 250,daily_price= 15,item_barcode="783521", passengers= 5,doors= 5, AC= "Yes", fuel="Diesel", baggage= "Yes", gear= "5, Manual", power= 100, co2=103 ,image= "peugeotcarro.jpeg", last_review=datetime.strptime("15/03/2023", "%d/%m/%Y").date(), next_review=datetime.strptime("15/03/2024", "%d/%m/%Y").date(), inspection=datetime.strptime("25/06/2023", "%d/%m/%Y").date(),desc="Discover the essence of practical elegance with the Skoda Fabia. This compact car is not just a mode of transportation; it's a testament to thoughtful design and intelligent engineering. /nWith its modern exterior and well-appointed interior, the Fabia effortlessly combines style with functionality. Step into a space that prioritizes comfort and versatility, creating an environment that enhances your daily drive. /nEfficiency takes center stage in the Fabia's agile performance and fuel economy. Maneuver through city streets with ease and embark on journeys with the assurance of reliability, making every drive a pleasure. /nThe Skoda Fabia is more than a car; it's a companion for the practical driver. Embrace the perfect blend of compact brilliance with a vehicle that excels in both form and function.")
        porscheP=Vehicle(item_name="Porsche",item_type= "Car", item_model= "Panamera" , item_price= 600,daily_price= 29,item_barcode="783522", passengers= 5,doors= 4, AC= "Yes", fuel="Hybrid", baggage= "Yes", gear= "8, Automatic", power= 265, co2=195 ,image= "porschecarro.jpeg", last_review=datetime.strptime("30/09/2023", "%d/%m/%Y").date(), next_review=datetime.strptime("30/09/2024", "%d/%m/%Y").date(), inspection=datetime.strptime("24/06/2023", "%d/%m/%Y").date(),desc="Step into a realm of automotive sophistication with the Mercedes Classe E. This executive sedan is not merely a car; it's an embodiment of luxury and cutting-edge technology that stands the test of time. /nFrom its graceful exterior lines to the meticulously crafted interior, the Classe E radiates timeless elegance. Immerse yourself in a haven of comfort and innovation where every detail speaks to Mercedes-Benz's unwavering commitment to excellence. /nPerformance takes center stage in the Classe E, with a potent engine and advanced driving dynamics that ensure a journey of pure exhilaration. Whether navigating city streets or embarking on long-distance drives, this sedan redefines the art of driving. /nThe Mercedes Classe E is more than a mode of transportation; it's a statement of refinement and prestige. Elevate your driving experience with a vehicle that seamlessly blends classic allure with modern innovation.")
        skodaFabia=Vehicle(item_name="Skoda",item_type= "Car", item_model= "Fabia" , item_price= 250,daily_price= 15,item_barcode="783523", passengers= 5,doors= 5, AC= "Yes", fuel="Gasoline", baggage= "Yes", gear= "6; Manual", power= 150, co2=131 ,image= "skodacarro.jpeg", last_review=datetime.strptime("29/03/2023", "%d/%m/%Y").date(), next_review=datetime.strptime("29/03/2024", "%d/%m/%Y").date(), inspection=datetime.strptime("11/06/2023", "%d/%m/%Y").date(),desc="Experience the perfect blend of style and efficiency with the Volkswagen Polo. This compact car isn't just a vehicle; it's a symbol of German engineering precision and contemporary design. /nWith its sleek exterior and thoughtfully designed interior, the Polo exudes modern charm. Step into a cockpit where comfort meets innovation, creating an environment that enhances every drive. /nEfficiency is at the heart of the Polo's dynamic performance and fuel economy. Whether navigating urban streets or embarking on a road trip, this car delivers a driving experience that is both enjoyable and practical. /nThe Volkswagen Polo is more than a car; it's a companion for the urban explorer. Embrace the excellence of German automotive craftsmanship with a vehicle that effortlessly combines compact design with driving pleasure.")
        mercedesCE=Vehicle(item_name="Mercedes",item_type= "Car", item_model= "Classe E" , item_price= 250,daily_price= 15,item_barcode="783524", passengers= 5,doors= 4, AC= "Yes", fuel="Hybrid", baggage= "Yes", gear= "9, Automatic", power= 156, co2=163 ,image= "mercedesclasseE.jpeg", last_review=datetime.strptime("19/04/2023", "%d/%m/%Y").date(), next_review=datetime.strptime("19/04/2024", "%d/%m/%Y").date(), inspection=datetime.strptime("29/08/2023", "%d/%m/%Y").date(),desc="Embark on a journey of refined power and modern luxury with the Volkswagen Touareg. This SUV isn't just a vehicle; it's a testament to Volkswagen's commitment to combining performance with sophistication. /nFrom its bold exterior to the meticulously crafted interior, the Touareg captivates with its seamless blend of style and functionality. Step into a realm where comfort meets cutting-edge technology, creating an oasis of serenity on every road. /nAdventure takes center stage with the Touareg's dynamic performance and versatile features. Whether conquering off-road trails or cruising through cityscapes, this SUV delivers an experience that goes beyond expectations. /nThe Volkswagen Touareg is more than an SUV; it's a companion for those who crave both the thrill of exploration and the luxury of modern living. Elevate your adventures with a vehicle that redefines the essence of driving.")
        volkswagenPolo=Vehicle(item_name="Volkswagen",item_type= "Car", item_model= "Polo" , item_price= 250,daily_price= 15,item_barcode="783525", passengers= 5,doors= 5, AC= "Yes", fuel="Gasoline", baggage= "Yes", gear= "6, Manual", power= 110, co2=123 ,image= "volkswagencarro (2).jpeg", last_review=datetime.strptime("17/03/2023", "%d/%m/%Y").date(), next_review=datetime.strptime("17/03/2024", "%d/%m/%Y").date(), inspection=datetime.strptime("25/06/2023", "%d/%m/%Y").date(),desc="Unleash the spirit of urban riding with the Yamaha MT 125. This sporty and nimble motorcycle isn't just a bike; it's a symbol of Yamaha's dedication to delivering exhilarating performance and cutting-edge design. /nFrom its sleek and aggressive exterior to the precision-engineered components, the MT 125 stands out as a street conqueror. Take a seat in the saddle and feel the perfect fusion of comfort and control, creating a riding experience that excites every sense. /nPerformance is at the core of the MT 125's DNA, with a responsive engine and agile handling that effortlessly navigate city streets. Whether commuting or carving through twists and turns, this motorcycle embodies the essence of urban riding. /nThe Yamaha MT 125 is more than a two-wheeled machine; it's a companion for those who crave the thrill of the road. Elevate your ride with a motorcycle that redefines the art of mastering the streets with style.")
        volkswagenP=Vehicle(item_name="Volkswagen",item_type= "Car", item_model= "Polo" , item_price= 250,daily_price= 15,item_barcode="783526", passengers= 5,doors= 5, AC= "Yes", fuel="Diesel", baggage= "Yes", gear= "6, Manual", power= 95, co2=123 ,image= "volkswagencarro.jpeg", last_review=datetime.strptime("25/07/2023", "%d/%m/%Y").date(), next_review=datetime.strptime("25/07/2024", "%d/%m/%Y").date(), inspection=datetime.strptime("07/04/2023", "%d/%m/%Y").date(),desc="Conquer the trails and embrace the thrill of off-road adventures with the Honda TRX400. This all-terrain vehicle (ATV) isn't just a machine; it's a testament to Honda's legacy of engineering excellence and off-road prowess. /nFrom its rugged exterior to the robust chassis, the TRX400 stands ready for the challenges of the off-road terrain. Take the handlebars and experience a ride that seamlessly combines power with control, creating an ATV that excels in every environment. /nPerformance is at the heart of the TRX400, with a responsive engine and durable suspension system designed to handle varied landscapes. Whether navigating through mud, tackling hills, or cruising open trails, this ATV embodies the spirit of off-road dominance. /nThe Honda TRX400 is more than an off-road companion; it's a vehicle that invites you to explore the great outdoors with confidence. Elevate your off-road experiences with an ATV that defines the standard for rugged reliability.")
        volkswagenTuareg=Vehicle(item_name="Volkswagen",item_type= "Suv", item_model= "Tuareg" , item_price= 250,daily_price= 15,item_barcode="783527", passengers= 5,doors= 5, AC= "Yes", fuel="Diesel", baggage= "Yes", gear= "8, Automatic", power= 231, co2=175 ,image= "volkswagensuv.jpeg", last_review=datetime.strptime("13/03/2023", "%d/%m/%Y").date(), next_review=datetime.strptime("13/03/2024", "%d/%m/%Y").date(), inspection=datetime.strptime("17/05/2023", "%d/%m/%Y").date(),desc="Step into the realm of luxury and dynamic performance with the BMW X6. This Sports Activity Coupe (SAC) isn't just a vehicle; it's a fusion of BMW's iconic design and innovative engineering. /nFrom its commanding exterior presence to the meticulously crafted interior, the X6 exudes a blend of athleticism and opulence. Take a seat in the driver's cockpit and experience a journey where comfort meets cutting-edge technology, creating an immersive driving experience. /nPerformance takes center stage with the X6's powerful engine and precision handling. Whether navigating city streets or cruising on the open road, this SAC delivers a driving experience that seamlessly combines elegance with motion. /nThe BMW X6 is more than an SUV; it's a statement of modern luxury and bold design. Elevate your driving passion with a vehicle that redefines the boundaries of style and performance.")
        yamaha125=Vehicle(item_name="Yamaha",item_type= "Motorbike", item_model= "mt125" , item_price= 50,daily_price= 8,item_barcode="783528", passengers= 2,doors= 0, AC= "No", fuel="Gasoline", baggage= "No", gear= "6, Manual", power= 14.8, co2=99 ,image= "yamahamt125mota.jpeg", last_review=datetime.strptime("27/03/2023", "%d/%m/%Y").date(), next_review=datetime.strptime("27/03/2024", "%d/%m/%Y").date(), inspection=datetime.strptime("05/07/2023", "%d/%m/%Y").date(),desc="Discover the perfect synergy of agility and sophistication with the BMW Serie 1. This compact luxury car isn't just a vehicle; it's a testament to BMW's commitment to delivering a thrilling driving experience without compromising on style. /nFrom its sleek and aerodynamic exterior to the meticulously designed interior, the Serie 1 captures attention with its modern aesthetics. Take the driver's seat and feel the perfect balance of comfort and control, creating a dynamic driving environment. /nPerformance is at the heart of the Serie 1, with a responsive engine and advanced driving dynamics that redefine compact car standards. /n Whether navigating urban landscapes or cruising on the highway, this car delivers a driving experience that is both exhilarating and refined. /nThe BMW Serie 1 is more than a car; it's a companion for those who seek luxury in a compact form. Elevate your daily drives with a vehicle that effortlessly combines premium features with uncompromised performance.")
        hondaTrx=Vehicle(item_name="Honda",item_type= "Motorbike", item_model= "Trx400" , item_price= 50,daily_price= 8,item_barcode="783529", passengers= 2,doors= 0, AC= "No", fuel="Gasoline", baggage= "No", gear= "5, Manual", power= 23.5, co2=140 ,image= "Hondatrx400mota.jpeg", last_review=datetime.strptime("13/12/2023", "%d/%m/%Y").date(), next_review=datetime.strptime("13/12/2024", "%d/%m/%Y").date(), inspection=datetime.strptime("25/09/2023", "%d/%m/%Y").date(),desc="Experience the perfect blend of style and performance with the Renault Clio. This compact car isn't just a mode of transportation; it's a symbol of Renault's commitment to chic design and driving pleasure. /nFrom its expressive exterior to the thoughtfully designed interior, the Clio captures attention with its modern flair. Step into the driver's seat and feel the harmonious fusion of comfort and innovative features, creating a driving experience that resonates with the contemporary driver. /nPerformance takes center stage in the Clio, with a responsive engine and nimble handling that make every journey a delightful adventure. Whether navigating city streets or embarking on a weekend getaway, this car delivers a driving experience that is both dynamic and sophisticated. /nThe Renault Clio is more than a car; it's a companion for those who appreciate chic design without compromising on performance. Elevate your daily drives with a vehicle that embodies the essence of chic sophistication.")
        bmwx6=Vehicle(item_name="Bmw",item_type= "Suv", item_model= "X6" , item_price= 250,daily_price= 15,item_barcode="783530", passengers= 5,doors= 5, AC= "Yes", fuel="Hybrid", baggage= "Yes", gear= "8, Automatic", power= 265, co2=234 ,image= "bmwcarro.jpeg", last_review=datetime.strptime("10/05/2023", "%d/%m/%Y").date(), next_review=datetime.strptime("10/05/2024", "%d/%m/%Y").date(), inspection=datetime.strptime("15/12/2023", "%d/%m/%Y").date(),desc="Embark on a journey of urban exploration with the Peugeot 2008. This compact SUV isn't just a vehicle; it's a manifestation of Peugeot's commitment to style and versatility in the cityscape. /nWith its sleek exterior design and well-crafted interior, the 2008 captivates with its modern aesthetics. Step inside and experience a blend of comfort and technology, creating a driving environment that adapts to the contemporary lifestyle. /nEfficiency takes center stage with the 2008's agile performance and fuel economy. Whether navigating crowded streets or setting out on a weekend escape, this SUV delivers a driving experience that seamlessly blends city chic with dynamic capability. /nThe Peugeot 2008 is more than an SUV; it's a companion for urban adventurers. Elevate your city drives with a vehicle that effortlessly combines modern design with the versatility needed for the urban landscape.")
        bmwS1=Vehicle(item_name="Bmw",item_type= "Car", item_model= "Serie 1" , item_price= 250,daily_price= 15,item_barcode="783531", passengers= 5,doors= 5, AC= "Yes", fuel="Hybrid", baggage= "Yes", gear= "8, Automatic", power= 116, co2=114 ,image= "bmwcarro2.jpeg", last_review=datetime.strptime("24/03/2023", "%d/%m/%Y").date(), next_review=datetime.strptime("24/03/2024", "%d/%m/%Y").date(), inspection=datetime.strptime("16/11/2023", "%d/%m/%Y").date(),desc="Discover the perfect synergy of agility and sophistication with the BMW Serie 1. This compact luxury car isn't just a vehicle; it's a testament to BMW's commitment to delivering a thrilling driving experience without compromising on style. /nFrom its sleek and aerodynamic exterior to the meticulously designed interior, the Serie 1 captures attention with its modern aesthetics. Take the driver's seat and feel the perfect balance of comfort and control, creating a dynamic driving environment. /nPerformance is at the heart of the Serie 1, with a responsive engine and advanced driving dynamics that redefine compact car standards. /n Whether navigating urban landscapes or cruising on the highway, this car delivers a driving experience that is both exhilarating and refined. /nThe BMW Serie 1 is more than a car; it's a companion for those who seek luxury in a compact form. Elevate your daily drives with a vehicle that effortlessly combines premium features with uncompromised performance.")
        renaultC=Vehicle(item_name="Renault",item_type= "Car", item_model= "Clio" , item_price= 50,daily_price= 8,item_barcode="783532", passengers= 5,doors= 5, AC= "Yes", fuel="Eletric", baggage= "Yes", gear= "6, Manual", power= 155, co2=102 ,image= "renaultcarro.jpeg", last_review=datetime.strptime("10/09/2023", "%d/%m/%Y").date(), next_review=datetime.strptime("10/09/2024", "%d/%m/%Y").date(), inspection=datetime.strptime("03/10/2023", "%d/%m/%Y").date(),desc="Experience the perfect blend of style and performance with the Renault Clio. This compact car isn't just a mode of transportation; it's a symbol of Renault's commitment to chic design and driving pleasure. /nFrom its expressive exterior to the thoughtfully designed interior, the Clio captures attention with its modern flair. Step into the driver's seat and feel the harmonious fusion of comfort and innovative features, creating a driving experience that resonates with the contemporary driver. /nPerformance takes center stage in the Clio, with a responsive engine and nimble handling that make every journey a delightful adventure. Whether navigating city streets or embarking on a weekend getaway, this car delivers a driving experience that is both dynamic and sophisticated. /nThe Renault Clio is more than a car; it's a companion for those who appreciate chic design without compromising on performance. Elevate your daily drives with a vehicle that embodies the essence of chic sophistication.")
        peugeot2008=Vehicle(item_name="Peugeot",item_type= "Car", item_model= "2008" , item_price= 250,daily_price= 15,item_barcode="783533", passengers= 5,doors= 5, AC= "Yes", fuel="Hybrid", baggage= "Yes", gear= "6, Manual", power= 136, co2=125 ,image= "peugeotcarro2.jpeg", last_review=datetime.strptime("25/08/2023", "%d/%m/%Y").date(), next_review=datetime.strptime("25/08/2024", "%d/%m/%Y").date(), inspection=datetime.strptime("07/09/2023", "%d/%m/%Y").date(),desc="Embark on a journey of urban exploration with the Peugeot 2008. This compact SUV isn't just a vehicle; it's a manifestation of Peugeot's commitment to style and versatility in the cityscape. /nWith its sleek exterior design and well-crafted interior, the 2008 captivates with its modern aesthetics. Step inside and experience a blend of comfort and technology, creating a driving environment that adapts to the contemporary lifestyle. /nEfficiency takes center stage with the 2008's agile performance and fuel economy. Whether navigating crowded streets or setting out on a weekend escape, this SUV delivers a driving experience that seamlessly blends city chic with dynamic capability. /nThe Peugeot 2008 is more than an SUV; it's a companion for urban adventurers. Elevate your city drives with a vehicle that effortlessly combines modern design with the versatility needed for the urban landscape.")
        opelC=Vehicle(item_name="Opel",item_type= "Car", item_model= "Corsa" , item_price= 50,daily_price= 8,item_barcode="783534", passengers= 5,doors= 5, AC= "Yes", fuel="Gasoline", baggage= "Yes", gear= "6, Manual", power= 136, co2=102 ,image= "opelcarro2.jpeg", last_review=datetime.strptime("09/03/2023", "%d/%m/%Y").date(), next_review=datetime.strptime("09/03/2024", "%d/%m/%Y").date(), inspection=datetime.strptime("25/11/2023", "%d/%m/%Y").date(),desc="Discover the perfect fusion of style and performance with the Opel Corsa. This compact car isn't just a mode of transportation; it's a testament to Opel's dedication to providing a dynamic and stylish driving experience. /nFrom its chic exterior design to the intelligently designed interior, the Corsa captivates with its modern allure. Step into the driver's seat and feel the harmonious blend of comfort and cutting-edge features, creating a driving experience that resonates with the modern driver. /nEfficiency is at the forefront of the Corsa's agile performance and fuel economy. Whether navigating urban streets or embarking on a spontaneous road trip, this car delivers a driving experience that effortlessly combines style with everyday dynamism. /nThe Opel Corsa is more than a car; it's a companion for those who appreciate sleek design without compromising on performance. Elevate your daily drives with a vehicle that embodies the essence of effortless style.")
        volkswagenP2=Vehicle(item_name="Volkswagen",item_type= "Car", item_model= "Polo" , item_price= 250,daily_price= 15,item_barcode="783535", passengers= 5,doors= 5, AC= "Yes", fuel="Gasoline", baggage= "Yes", gear= "6, Manual", power= 110, co2=123 ,image= "volswagencarro2.jpeg", last_review=datetime.strptime("10/10/2023", "%d/%m/%Y").date(), next_review=datetime.strptime("10/10/2024", "%d/%m/%Y").date(), inspection=datetime.strptime("29/06/2023", "%d/%m/%Y").date(),desc="Immerse yourself in the epitome of driving pleasure with the Volkswagen Polo. This compact car isn't just a vehicle; it's a symbol of Volkswagen's commitment to blending style with exhilarating performance. /nFrom its contemporary exterior design to the well-crafted interior, the Polo stands out with its modern aesthetics. Step into the driver's seat and experience the perfect fusion of comfort and advanced features, creating a driving environment that caters to the discerning driver. /nEfficiency takes center stage with the Polo's nimble performance and fuel efficiency. Whether navigating city streets or embarking on a weekend adventure, this car delivers a driving experience that seamlessly combines style with everyday practicality. /nThe Volkswagen Polo is more than a car; it's a companion for those who seek driving pleasure without compromise. Elevate your daily commutes with a vehicle that embodies the essence of style and performance.")
        smartF2=Vehicle(item_name="Smart",item_type= "Car", item_model= "Fortwo" , item_price= 50,daily_price= 8,item_barcode="783536", passengers= 2,doors= 3, AC= "Yes", fuel="Gasoline", baggage= "Yes", gear= "6, Manual", power= 80, co2=88 ,image= "smartcarro.jpeg", last_review=datetime.strptime("10/12/2023", "%d/%m/%Y").date(), next_review=datetime.strptime("10/12/2024", "%d/%m/%Y").date(), inspection=datetime.strptime("26/03/2023", "%d/%m/%Y").date(),desc="Navigate the urban landscape with unmatched agility and style in the Smart Fortwo. This compact car isn't just a vehicle; it's a testament to Smart's dedication to redefining city driving with compact brilliance. /nFrom its distinctive exterior design to the ingeniously designed interior, the Fortwo captivates with its modern charm. Slide into the driver's seat and experience a perfect blend of comfort and smart features, creating a driving experience tailored for the urban adventurer. /nEfficiency takes center stage with the Fortwo's nimble performance and compact size, making city maneuvering a breeze. Whether weaving through traffic or finding the perfect parking spot, this car delivers a driving experience that seamlessly combines style with urban practicality. /nThe Smart Fortwo is more than a car; it's a companion for those who embrace city living with flair. Elevate your urban adventures with a vehicle that embodies the essence of compact brilliance and urban agility.")
        toyotaC=Vehicle(item_name="Toyota",item_type= "Car", item_model= "Corola" , item_price= 50,daily_price= 8,item_barcode="783537", passengers= 5,doors= 5, AC= "Yes", fuel="Hybrid", baggage= "Yes", gear= "6, Automatic", power= 123, co2=86 ,image= "toyotacarro.jpeg", last_review=datetime.strptime("12/05/2023", "%d/%m/%Y").date(), next_review=datetime.strptime("12/05/2024", "%d/%m/%Y").date(), inspection=datetime.strptime("28/06/2023", "%d/%m/%Y").date(),desc="Embark on a journey of refined driving with the Toyota Corolla. This compact sedan isn't just a car; it's a symbol of Toyota's commitment to delivering timeless elegance and modern performance. /nFrom its sleek exterior to the thoughtfully designed interior, the Corolla captures attention with its understated sophistication. Step into the driver's seat and experience a perfect balance of comfort and advanced features, creating a driving experience that transcends the ordinary. /nEfficiency takes center stage with the Corolla's reliable performance and fuel efficiency. Whether navigating city streets or embarking on a road trip, this sedan delivers a driving experience that seamlessly combines style with everyday practicality. /nThe Toyota Corolla is more than a car; it's a companion for those who appreciate a touch of elegance in their daily drives. Elevate your journeys with a vehicle that embodies the essence of timeless design and modern reliability.")
        SeatL=Vehicle(item_name="Seat",item_type= "Car", item_model= "Leon" , item_price= 50,daily_price= 8,item_barcode="783538", passengers= 5,doors= 5, AC= "Yes", fuel="Natural Gas", baggage= "Yes", gear= "7, Automatic", power= 98, co2=104 ,image= "Seatcarro.jpeg", last_review=datetime.strptime("10/03/2023", "%d/%m/%Y").date(), next_review=datetime.strptime("10/03/2024", "%d/%m/%Y").date(), inspection=datetime.strptime("10/08/2023", "%d/%m/%Y").date(),desc="Embark on a thrilling driving experience with the Seat Leon. This compact car isn't just a mode of transportation; it's a manifestation of Seat's dedication to dynamic performance and contemporary design. /nFrom its bold exterior lines to the meticulously crafted interior, the Leon captivates with its modern aesthetics. Take the driver's seat and feel the perfect fusion of comfort and cutting-edge features, creating a driving environment that resonates with the modern driver. /nPerformance is at the forefront of the Leon's DNA, with a responsive engine and agile handling that redefine the compact car experience. Whether navigating urban streets or cruising on the open road, this car delivers a driving experience that seamlessly blends style with exhilaration. /nThe Seat Leon is more than a car; it's a companion for those who seek dynamic driving without compromise. Elevate your daily commutes with a vehicle that embodies the essence of contemporary style and spirited performance.")
        MercedesCls=Vehicle(item_name="Mercedes",item_type= "Car", item_model= "Cls" , item_price= 250,daily_price= 15,item_barcode="783539", passengers= 5,doors= 5, AC= "Yes", fuel="Gasoline", baggage= "Yes", gear= "6, Manual", power= 115, co2=114 ,image= "Mercedescarro.jpeg", last_review=datetime.strptime("15/05/2023", "%d/%m/%Y").date(), next_review=datetime.strptime("15/05/2024", "%d/%m/%Y").date(), inspection=datetime.strptime("12/07/2023", "%d/%m/%Y").date(),desc="Dive into an unparalleled driving adventure with the Mercedes CLS. This executive coupe is not just a vehicle; it's a testament to Mercedes-Benz's commitment to luxurious performance and avant-garde design./nFrom its sweeping exterior curves to the exquisitely designed interior, the CLS enchants with its sophisticated aesthetics. Slide into the driver's seat and embrace the harmonious blend of opulence and state-of-the-art features, crafting a driving sanctuary that aligns with the expectations of the contemporary elite./nPerformance lies at the heart of the CLS's ethos, with a potent engine and nimble handling that elevate the executive coupe category. Whether threading through city lanes or accelerating on highways, this car offers a driving experience that perfectly marries elegance with thrill./nThe Mercedes CLS is more than a car; it's a partner for those who demand luxurious driving without compromise. Enhance your journeys with a vehicle that captures the spirit of modern luxury and dynamic performance.")
        db.session.add(audiR81)
        db.session.add(audiR82)
        db.session.add(audiQ71)
        db.session.add(audiQ72)
        db.session.add(citroenC4)
        db.session.add(fordRanger)
        db.session.add(mercedesA)
        db.session.add(mercedesslk)
        db.session.add(mercedesCE)
        db.session.add(opelAstra)
        db.session.add(peugeot207)
        db.session.add(porscheP)
        db.session.add(skodaFabia)
        db.session.add(mercedesCE)
        db.session.add(volkswagenPolo)
        db.session.add(volkswagenP)
        db.session.add(volkswagenTuareg)
        db.session.add(yamaha125)
        db.session.add(hondaTrx)
        db.session.add(bmwx6)
        db.session.add(bmwS1)
        db.session.add(renaultC)
        db.session.add(peugeot2008)
        db.session.add(opelC)
        db.session.add(volkswagenP2)
        db.session.add(smartF2)
        db.session.add(toyotaC)
        db.session.add(SeatL)
        db.session.add(MercedesCls)
        
        
        db.session.commit()
        db.session.close()
        
else:
    print("base de dados ja existentes")        
        